//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class GamesSomeGamer
    {
        public int Id { get; set; }
        public long IdPlayer { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<long> Numbers { get; set; }
        public string Win { get; set; }
    }
}
