//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BaldaEntities : DbContext
    {
        public BaldaEntities()
            : base("name=BaldaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Dictionary> Dictionaries { get; set; }
        public DbSet<Dictionary10> Dictionary10 { get; set; }
        public DbSet<Dictionary11> Dictionary11 { get; set; }
        public DbSet<Dictionary12> Dictionary12 { get; set; }
        public DbSet<Dictionary13> Dictionary13 { get; set; }
        public DbSet<Dictionary14> Dictionary14 { get; set; }
        public DbSet<Dictionary15> Dictionary15 { get; set; }
        public DbSet<Dictionary16> Dictionary16 { get; set; }
        public DbSet<Dictionary17> Dictionary17 { get; set; }
        public DbSet<Dictionary18> Dictionary18 { get; set; }
        public DbSet<Dictionary19> Dictionary19 { get; set; }
        public DbSet<Dictionary20> Dictionary20 { get; set; }
        public DbSet<Dictionary21> Dictionary21 { get; set; }
        public DbSet<Dictionary22> Dictionary22 { get; set; }
        public DbSet<Dictionary23> Dictionary23 { get; set; }
        public DbSet<Dictionary24> Dictionary24 { get; set; }
        public DbSet<Dictionary25> Dictionary25 { get; set; }
        public DbSet<Dictionary26> Dictionary26 { get; set; }
        public DbSet<Dictionary27> Dictionary27 { get; set; }
        public DbSet<Dictionary28> Dictionary28 { get; set; }
        public DbSet<Dictionary29> Dictionary29 { get; set; }
        public DbSet<Dictionary3> Dictionary3 { get; set; }
        public DbSet<Dictionary30> Dictionary30 { get; set; }
        public DbSet<Dictionary31> Dictionary31 { get; set; }
        public DbSet<Dictionary32> Dictionary32 { get; set; }
        public DbSet<Dictionary4> Dictionary4 { get; set; }
        public DbSet<Dictionary5> Dictionary5 { get; set; }
        public DbSet<Dictionary6> Dictionary6 { get; set; }
        public DbSet<Dictionary7> Dictionary7 { get; set; }
        public DbSet<Dictionary8> Dictionary8 { get; set; }
        public DbSet<Dictionary9> Dictionary9 { get; set; }
        public DbSet<Game> Games { get; set; }
        public DbSet<Gamer> Gamers { get; set; }
        public DbSet<GamesSomeGamer> GamesSomeGamers { get; set; }
        public DbSet<ListOfGamer> ListOfGamers { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Word> Words { get; set; }
    }
}
